# Generated by Django 2.1.3 on 2018-11-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('date_birth', models.DateTimeField()),
                ('phone', models.CharField(max_length=20)),
                ('npwp', models.CharField(max_length=20)),
                ('ktp', models.CharField(max_length=20)),
            ],
        ),
    ]
