# Generated by Django 2.1.3 on 2018-11-20 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_status_loan'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers_rel_loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loans', models.IntegerField()),
                ('time_period', models.IntegerField(blank=True, default=None, null=True)),
                ('interest_rate', models.FloatField(blank=True, default=None, null=True)),
                ('installment', models.IntegerField(blank=True, default=None, null=True)),
                ('interest_monthly', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_birth',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='customers_rel_loan',
            name='custid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='customers_rel_loan',
            name='loanid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Loan'),
        ),
    ]
