# Generated by Django 2.1.3 on 2018-11-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20181113_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers_rel_loan',
            name='installment',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customers_rel_loan',
            name='interest_monthly',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customers_rel_loan',
            name='interest_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
