# Generated by Django 2.1.3 on 2018-11-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20181113_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers_rel_loan',
            name='time_period',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
