# Generated by Django 2.1.3 on 2018-11-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customers_rel_loan_time_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers_rel_loan',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
