# Generated by Django 2.1.3 on 2018-11-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customers_rel_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_birth',
            field=models.DateField(),
        ),
    ]
